language: perl

install:
  - sudo apt-get update
  - sudo apt-get install libarchive-dev
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing |cpanm -n
  - cpanm -n Exporter::Tidy
  - cpanm -n FFI::Raw
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true
  - cpanm -n Pod::Abstract
  - cpanm -n FFI::Util

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"

env:
  - ALIEN_LIBARCHIVE=share
  - ALIEN_LIBARCHIVE=system

script:
  - cpanm -n -v Alien::Libarchive
  - dzil test -v
