language: perl

sudo: false

addons:
  apt:
    packages:
      - libarchive-dev

install:
  - ./maint/travis-install-mods
  - dzil -I. authordeps --missing | grep -v inc::SeeAlso |cpanm -n
  - dzil -I. listdeps --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

matrix:
  global:
    - ALIEN_BASE_NO_ABMB=1
  env:
    - ALIEN_LIBARCHIVE=share
    - ALIEN_LIBARCHIVE=system

script:
  - dzil -I. test -v
